#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 2.7 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init (void);

/* Output assignments (and their defaults if specified) */
#define sct_fsm_OUTPUT_Output_pin_0 (0)
#define sct_fsm_OUTPUT_Output_pin_1 (1)

#define sct_fsm_setOutputDefault() do {LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x00000000) | 0x00000000;} while(0)


/* Match register reload macro definitions */
#define sct_fsm_reload_Match1_a(value) do {LPC_SCT->MATCHREL[0].L = value;} while(0)
#define sct_fsm_reload_Match1_b(value) do {LPC_SCT->MATCHREL[1].L = value;} while(0)
#define sct_fsm_reload_Match2_a(value) do {LPC_SCT->MATCHREL[2].L = value;} while(0)
#define sct_fsm_reload_Match2_b(value) do {LPC_SCT->MATCHREL[3].L = value;} while(0)

#endif
