
/* Generated by fzmparser version 2.7 --- DO NOT EDIT! */

/* Uses following resources: */
/* 4 events, 1+0 states, 0 inputs, 2 outputs, 4+0 match regs, 0+0 capture regs */

#include "sct_fsm.h"


void sct_fsm_init (void)
{
LPC_SCT->CONFIG = (LPC_SCT->CONFIG & ~0x00060001) | 0x00000000; /* SPLIT */

/* MATCH/CAPTURE registers */
LPC_SCT->REGMODE_L = 0x0000;         /* L: 4x MATCH, 0x CAPTURE, 1 unused */
LPC_SCT->REGMODE_H = 0x0000;             /* H: 0x MATCH, 0x CAPTURE, 5 unused */
LPC_SCT->MATCH[0].L = Match_Count1_a;             /* Match1_a */
LPC_SCT->MATCHREL[0].L = Match_Count1_a;
LPC_SCT->MATCH[1].L = Match_Count1_b;             /* Match1_b */
LPC_SCT->MATCHREL[1].L = Match_Count1_b;
LPC_SCT->MATCH[2].L = Match_Count2_a;             /* Match2_a */
LPC_SCT->MATCHREL[2].L = Match_Count2_a;
LPC_SCT->MATCH[3].L = Match_Count2_b;             /* Match2_b */
LPC_SCT->MATCHREL[3].L = Match_Count2_b;

/* OUTPUT registers */
LPC_SCT->OUT[0].SET = 0x00000002;        /* Output_pin_0 */
LPC_SCT->OUT[0].CLR = 0x00000001;
LPC_SCT->OUT[1].SET = 0x00000004;        /* Output_pin_1 */
LPC_SCT->OUT[1].CLR = 0x00000008;
  /* Unused outputs must not be affected by any event */
LPC_SCT->OUT[2].SET = 0;
LPC_SCT->OUT[2].CLR = 0;
LPC_SCT->OUT[3].SET = 0;
LPC_SCT->OUT[3].CLR = 0;

/* Conflict resolution register */

/* EVENT registers */
LPC_SCT->EVENT[0].CTRL = 0x00005000;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[0].STATE = 0x00000001;
LPC_SCT->EVENT[1].CTRL = 0x00005001;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[1].STATE = 0x00000001;
LPC_SCT->EVENT[2].CTRL = 0x00005003;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[2].STATE = 0x00000001;
LPC_SCT->EVENT[3].CTRL = 0x00005002;     /* L: --> state L_ENTRY */
LPC_SCT->EVENT[3].STATE = 0x00000001;
  /* Unused events must not have any effect */
LPC_SCT->EVENT[4].STATE = 0;
LPC_SCT->EVENT[5].STATE = 0;

/* STATE registers */
LPC_SCT->STATE_L = 0;
LPC_SCT->STATE_H = 0; /* implicit value */

/* state names assignment: */
  /* State L 0: L_ENTRY */

/* CORE registers */
LPC_SCT->START_L = 0x0000;
LPC_SCT->STOP_L =  0x0000;
LPC_SCT->HALT_L =  0x0000;
LPC_SCT->LIMIT_L = 0x0009;
LPC_SCT->START_H = 0x0000;
LPC_SCT->STOP_H =  0x0000;
LPC_SCT->HALT_H =  0x0000;
LPC_SCT->LIMIT_H = 0x0000;
LPC_SCT->EVEN =    0x00000000;

}
